document.addEventListener("DOMContentLoaded", () => {
    const translations = {
        en: {
            // index.html
            "title": "DSON | Multimedia Design Portfolio",
            "nav-home": "Home",
            "nav-portfolio": "Portfolio",
            "nav-illustration": "Illustrations",
            "nav-3dmodeling": "3D Modeling",
            "nav-photo": "Photos",
            "nav-video": "Videos",
            "nav-uiux": "UI/UX",
            "nav-socialmedia": "Social Media",
            "nav-contact": "Contact Me",
            "about-title": "About Me",
            "about-1": `Hi! I’m <strong>Chang Dick Shen</strong>, but you can call me <strong>DSON</strong>. I'm a multimedia design student with a deep passion for crafting engaging and meaningful digital experiences. My expertise includes video editing, UI/UX design, and I also enjoy exploring the creative worlds of animation and game design.`,
            "about-2": `I actively share my creative content across multiple platforms, including <strong><a href="https://www.youtube.com/@dson.0404" target="_blank">YouTube</a></strong>, <strong><a href="https://space.bilibili.com/318162425/" target="_blank">Bilibili</a></strong>, <strong><a href="https://www.instagram.com/dson_04/" target="_blank">Instagram</a></strong>, <strong><a href="https://www.tiktok.com/@dson.04" target="_blank">TikTok</a></strong>, <strong><a href="https://www.xiaohongshu.com/user/profile/5d60f1db00000000010029cf" target="_blank">Xiaohongshu</a></strong>, and <strong><a href="https://twitter.com/DSON_04" target="_blank">X (Twitter)</a></strong>. Among these platforms, YouTube and Bilibili are my primary spaces for sharing my creative work.`,
            "about-3": `My mission is to transform creativity into work that resonates, inspires, and connects. Feel free to browse my portfolio or reach out through social media—I’d love to share my passion with you!`,
            "footer-text": "© 2025 DSON. All rights reserved.",
            // 3d-modeling.html
            "title-section-1": "3D Modeling Interior Design",
            "title-section-2": "3D Character Design & Environment Design Video Showreel",
            "title-section-3": "Product 3D Modeling",
            "video-caption": "My 3D Character Design & Environment Design Video Showreel.",
            "alt-final-2": "Kitchen side angle (right)",
            "alt-final-3": "Kitchen side angle (left)",
            "alt-final-4": "Kitchen front angle",
            "alt-final-5": "Kitchen left angle (close up)",
            "alt-final-6": "Kitchen right angle (close up)",
            "keyboard-1": "Mechanical Keyboard 3D Modeling 1",
            "keyboard-2": "Mechanical Keyboard 3D Modeling 2",
            "keyboard-3": "Mechanical Keyboard 3D Modeling 3",
            "keyboard-4": "Mechanical Keyboard 3D Modeling 4",
            "keyboard-5": "Mechanical Keyboard 3D Modeling 5",
            "keyboard-6": "Mechanical Keyboard 3D Modeling 6",
            // 404.html
            "title": "404 Not Found",
            "error-title": "404 - Page Not Found",
            "error-text": "The page you are looking for does not exist.",
            // contact.html
            "contact-title": "Write Something for Me!",
            "contact-name": "Name (Full Name or Nickname)",
            "contact-gender": "Gender (Male / Female)",
            "contact-age": "Age (0 ~ 99+)",
            "contact-email": "Email",
            "contact-message": "Message",
            "contact-btn": "Send!",
            // illustration.html
            "title-illustration": "DSON | Image Manipulation & Pixel Art",
            "section-image-manipulation": "Image Manipulation",
            "section-pixel-arts": "Pixel Arts",
            "img-apocalypse": "Apocalypse",
            "img-substance": "Substance Abuse",
            "pixel-boy": "2D Game Character (Boy)",
            "pixel-girl": "2D Game Character (Girl)",
            "pixel-soldier": "Pixel Soldier",
            "pixel-poster": "Pixel Art Poster",
            // photo.html
            "title": "DSON Photography | Daytime, Night & Motion Photography Portfolio",
            "photo-day": "Daytime Photography",
            "photo-night": "Dusk or Night Photography",
            "photo-motion": "Motion and Depth of Field",
            "photo-edit": "Photo Editing",
            "edit-chess": "Chess Neon Light Effect",
            "edit-cyber": "Cyberpunk Street Effect",
            "edit-80s": "80's Nostalgic Style",
            "edit-makoto": "Shinkai Makoto Style Effect",
            "edit-city": "City Night Scene Effect",
            "alt-day-1": "Daytime photography shot 1",
            "alt-day-2": "Daytime photography shot 2",
            "alt-day-3": "Daytime photography shot 3",
            "alt-day-4": "Daytime photography shot 4",
            "alt-day-5": "Daytime photography shot 5",
            "alt-day-6": "Daytime photography shot 6",
            "alt-day-7": "Daytime photography shot 7",
            "alt-day-8": "Daytime photography shot 8",
            "alt-dusk-1": "Dusk photography shot 1",
            "alt-dusk-2": "Dusk photography shot 2",
            "alt-dusk-3": "Dusk photography shot 3",
            "alt-dusk-4": "Dusk photography shot 4",
            "alt-night-1": "Night photography shot 1",
            "alt-night-2": "Night photography shot 2",
            "alt-night-3": "Night photography shot 3",
            "alt-night-4": "Night photography shot 4",
            "alt-fast-1": "Fast shutter motion shot 1",
            "alt-fast-2": "Fast shutter motion shot 2",
            "alt-slow-1": "Slow shutter motion blur shot 1",
            "alt-slow-2": "Slow shutter motion blur shot 2",
            "alt-depth-1": "Greater depth of field shot 1",
            "alt-depth-2": "Greater depth of field shot 2",
            "alt-shallow-1": "Shallow depth of field shot 1",
            "alt-shallow-2": "Shallow depth of field shot 2",
            // social-media.html
            "title": "DSON Social Media Portfolio | YouTube, Bilibili, Instagram, TikTok Stats",
            "socialmedia-title": "Social Media",
            "socialmedia-page": "Social Media Page",
            "socialmedia-click": "Click the page to see more data!",
            "alt-yt": "YouTube Page",
            "alt-bili": "Bilibili Page",
            "alt-ig": "Instagram Page",
            "alt-x": "X Profile Page",
            "alt-tt": "TikTok Page",
            "alt-xhs": "Xiaohongshu Page",
            "stats-subs": "Subscribers:",
            "stats-followers": "Followers:",
            "stats-totalviews": "Total views:",
            "date-suffix": "(19/05/2025)",
            // socialmedia.html
            "title-uiux": "DSON UI/UX Portfolio | Mobile App & Web Interface Designs",
            "section-uiux": "UI/UX Designs",
            "uiux-ocean-title": "Ocean Guardian",
            "uiux-ocean-desc": "Ocean Guardian is a mobile app that raises awareness about marine pollution and encourages users to take action. It provides ecosystem notifications, promotes volunteer activities, and lets users share achievements. The app aims to build a community that helps restore and protect our oceans, making them cleaner and more vibrant.",
            "uiux-mnowner-title": "MnOwner",
            "uiux-mnowner-desc": "MnOwner helps solve Malaysia’s double parking problem by reminding drivers to park responsibly. It reduces conflicts, saves time, and creates a more considerate parking culture, while supporting smoother traffic and community convenience.",
            "uiux-partners": "(My partners, Kai & Kean)",
            // video.html
            "title-video": "DSON Video Portfolio | Short Films, Animation, Motion Graphics & Editing",
            "section-shortfilm": "Short Film",
            "caption-klcity": "KL City Scene - A short film showcasing the vibrant cityscape of Kuala Lumpur.",
            "caption-scammer": "Say No To Scammer - An anti-fraud short film with twists and turns. (My partners, Kai & Kean)",
            "section-animation": "Animation Video",
            "caption-littlefox-teaser": "Little Fox Childish Adventure teaser - A teaser of the animation video. (Animated by my partner, Kean)",
            "caption-littlefox-full": "Little Fox Childish Adventure - A short animation video. (Animated by my partner, Kean)",
            "caption-motion-final": "Motion Graphic Final Assignment - Animated by my partner, Kean",
            "section-motiongraphic": "Motion Graphic",
            "caption-dsonintro": "DSON Intro - My YouTube videos' intro.",
            "caption-mco": "MCO - Typography motion video.",
            "caption-spiderman": "Spider-Man - Movie trailer.",
            "caption-visualmusic": "Visual Music.",
            "caption-mixmedia": "Mix Media.",
            "section-moviedubbing": "Movie Dubbing",
            "caption-ipman1": "Ip Man Final Season Fighting Part - Redubbed the audio.",
            "caption-ipman2": "Ip Man spoof trailer - Edited by 小芃路子野 and I redubbed the audio.",
            "section-productvideo": "Product Video",
            "caption-aula": "AULA F75 Mechanical Keyboard Product Video.",
            "section-psvideo": "Public Service Video",
            "caption-corruption": "Corruption Public Service Video.",
            "section-musicvideo": "Music Video",
            "caption-luv": "LUV (Ori Music 'Blue' - Yung Kai) - Music Video Remake.",
            "caption-codm": "CODM WC 2025 Unofficial Music Video.",
        },
        zh: {
            "title": "DSON | 多媒体设计作品集",
            "nav-home": "首页",
            "nav-portfolio": "作品集",
            "nav-illustration": "插画",
            "nav-3dmodeling": "3D建模",
            "nav-photo": "照片",
            "nav-video": "视频",
            "nav-uiux": "UI/UX",
            "nav-socialmedia": "社交媒体",
            "nav-contact": "联系我",
            "about-title": "关于我",
            "about-1": `你好！我是 <strong>郑迪绅（Chang Dick Shen）</strong>，你也可以叫我 <strong>DSON</strong>。我是一名多媒体设计学生，热爱创作引人入胜且富有意义的数字体验。我的专业领域包括视频剪辑、UI/UX 设计，同时也热衷于动画与游戏设计的创作过程。`,
            "about-2": `我会在多个平台分享我的创作内容，包括 <strong><a href="https://www.youtube.com/@dson.0404" target="_blank">YouTube</a></strong>、<strong><a href="https://space.bilibili.com/318162425/" target="_blank">Bilibili</a></strong>、<strong><a href="https://www.instagram.com/dson_04/" target="_blank">Instagram</a></strong>、<strong><a href="https://www.tiktok.com/@dson.04" target="_blank">TikTok</a></strong>、<strong><a href="https://www.xiaohongshu.com/user/profile/5d60f1db00000000010029cf" target="_blank">小红书</a></strong>、以及 <strong><a href="https://twitter.com/DSON_04" target="_blank">X（Twitter）</a></strong>。其中 YouTube 与 Bilibili 是我主要发布内容的平台。`,
            "about-3": `我的使命是将创意转化为能够引发共鸣、启发灵感并建立连接的作品。欢迎浏览我的作品集或通过社交媒体联系我！非常期待与您分享我的创作热情！`,
            "footer-text": "© 2025 DSON. 版权所有。",
            // 3d-modeling.html
            "title-section-1": "3D建模室内设计",
            "title-section-2": "3D角色与环境设计视频作品集",
            "title-section-3": "产品3D建模",
            "video-caption": "我的3D角色与环境设计视频作品集。",
            "alt-final-2": "厨房侧面角度（右）",
            "alt-final-3": "厨房侧面角度（左）",
            "alt-final-4": "厨房正面角度",
            "alt-final-5": "厨房左侧角度（特写）",
            "alt-final-6": "厨房右侧角度（特写）",
            "keyboard-1": "机械键盘3D建模1",
            "keyboard-2": "机械键盘3D建模2",
            "keyboard-3": "机械键盘3D建模3",
            "keyboard-4": "机械键盘3D建模4",
            "keyboard-5": "机械键盘3D建模5",
            "keyboard-6": "机械键盘3D建模6",
            // 404.html
            "title": "404 未找到",
            "error-title": "404 - 页面未找到",
            "error-text": "您访问的页面不存在。",
            // contact.html
            "contact-title": "写点什么给我吧！",
            "contact-name": "姓名（全名或昵称）",
            "contact-gender": "性别（男/女）",
            "contact-age": "年龄（0 ~ 99+）",
            "contact-email": "邮箱",
            "contact-message": "信息",
            "contact-btn": "发送！",
            // illustration.html
            "title-illustration": "DSON | 图像处理 & 像素艺术",
            "section-image-manipulation": "图像处理作品",
            "section-pixel-arts": "像素艺术",
            "img-apocalypse": "末日场景",
            "img-substance": "药物滥用",
            "pixel-boy": "2D 游戏角色（男）",
            "pixel-girl": "2D 游戏角色（女）",
            "pixel-soldier": "像素士兵",
            "pixel-poster": "像素海报",
            // photo.html
            "title": "DSON 摄影作品集｜白天、夜景与运动摄影作品",
            "photo-day": "白天摄影",
            "photo-night": "黄昏与夜景摄影",
            "photo-motion": "运动与景深摄影",
            "photo-edit": "照片编辑",
            "edit-chess": "棋盘霓虹灯效果",
            "edit-cyber": "赛博朋克街景效果",
            "edit-80s": "80年代怀旧风格",
            "edit-makoto": "新海诚风格效果",
            "edit-city": "城市夜景特效",
            "alt-day-1": "白天摄影 第1张",
            "alt-day-2": "白天摄影 第2张",
            "alt-day-3": "白天摄影 第3张",
            "alt-day-4": "白天摄影 第4张",
            "alt-day-5": "白天摄影 第5张",
            "alt-day-6": "白天摄影 第6张",
            "alt-day-7": "白天摄影 第7张",
            "alt-day-8": "白天摄影 第8张",
            "alt-dusk-1": "黄昏摄影 第1张",
            "alt-dusk-2": "黄昏摄影 第2张",
            "alt-dusk-3": "黄昏摄影 第3张",
            "alt-dusk-4": "黄昏摄影 第4张",
            "alt-night-1": "夜景摄影 第1张",
            "alt-night-2": "夜景摄影 第2张",
            "alt-night-3": "夜景摄影 第3张",
            "alt-night-4": "夜景摄影 第4张",
            "alt-fast-1": "高速快门运动摄影 第1张",
            "alt-fast-2": "高速快门运动摄影 第2张",
            "alt-slow-1": "低速快门动感模糊 第1张",
            "alt-slow-2": "低速快门动感模糊 第2张",
            "alt-depth-1": "大景深摄影 第1张",
            "alt-depth-2": "大景深摄影 第2张",
            "alt-shallow-1": "浅景深摄影 第1张",
            "alt-shallow-2": "浅景深摄影 第2张",
            // social-media.html
            "title": "DSON 社交媒体作品集 | YouTube、B站、IG、TikTok 数据展示",
            "socialmedia-title": "社交媒体",
            "socialmedia-page": "社交媒体页面",
            "socialmedia-click": "点击页面查看更多数据！",
            "alt-yt": "YouTube 页面",
            "alt-bili": "哔哩哔哩页面",
            "alt-ig": "Instagram 页面",
            "alt-x": "X（推特）页面",
            "alt-tt": "TikTok 页面",
            "alt-xhs": "小红书页面",
            "stats-subs": "订阅数：",
            "stats-followers": "粉丝数：",
            "stats-totalviews": "总浏览量：",
            "date-suffix": "(19/05/2025)",
            // socialmedia.html
            "title-uiux": "DSON UI/UX 作品集 | 移动应用与网页界面设计",
            "section-uiux": "UI/UX 设计",
            "uiux-ocean-title": "海洋守护者",
            "uiux-ocean-desc": "海洋守护者是一款提高海洋污染意识的移动应用，鼓励用户采取行动。应用提供生态系统通知、推广志愿者活动，并允许用户分享成就。该应用旨在建立一个社区，帮助恢复和保护我们的海洋，使其更清洁、更有生机。",
            "uiux-mnowner-title": "MnOwner",
            "uiux-mnowner-desc": "MnOwner 通过提醒司机规范停车，帮助解决马来西亚的双排问题。它减少冲突，节省时间，营造更有素养的停车文化，同时支持交通顺畅和社区便利。",
            "uiux-partners": "（我的合作伙伴，Kai & Kean）",
            // video.html
            "title-video": "DSON 视频作品集 | 短片、动画、动态影像与剪辑",
            "section-shortfilm": "短片",
            "caption-klcity": "吉隆坡城市景观短片，展示生动的都市风貌。",
            "caption-scammer": "拒绝诈骗短片——一部反诈骗短片，充满曲折。(我的伙伴：Kai & Kean)",
            "section-animation": "动画视频",
            "caption-littlefox-teaser": "小狐狸童趣冒险预告 - 动画视频预告。(动画由 Kean 制作)",
            "caption-littlefox-full": "小狐狸童趣冒险 - 短篇动画视频。(动画由 Kean 制作)",
            "caption-motion-final": "最终作业动画视频 - 动画由 Kean 制作",
            "section-motiongraphic": "动态影像",
            "caption-dsonintro": "DSON 片头 - 我的YouTube视频开场。",
            "caption-mco": "MCO - 字体动态影像视频。",
            "caption-spiderman": "蜘蛛侠 - 电影预告片。",
            "caption-visualmusic": "视觉音乐。",
            "caption-mixmedia": "混合媒体作品。",
            "section-moviedubbing": "影片配音",
            "caption-ipman1": "叶问最终季格斗片段 - 重新配音。",
            "caption-ipman2": "叶问恶搞预告 - 由小芃路子野编辑，我重新配音。",
            "section-productvideo": "产品视频",
            "caption-aula": "AULA F75 机械键盘产品视频。",
            "section-psvideo": "公益视频",
            "caption-corruption": "反贪污公益视频。",
            "section-musicvideo": "音乐视频",
            "caption-luv": "LUV (原曲 'Blue' - Yung Kai) - 音乐视频翻拍。",
            "caption-codm": "2025年CODM世锦赛非官方音乐视频。",
        },
        ms: {
            "title": "DSON | Portfolio Rekabentuk Multimedia",
            "nav-home": "Laman Utama",
            "nav-portfolio": "Portfolio",
            "nav-illustration": "Ilustrasi",
            "nav-3dmodeling": "Pemodelan 3D",
            "nav-photo": "Foto",
            "nav-video": "Video",
            "nav-uiux": "UI/UX",
            "nav-socialmedia": "Media Sosial",
            "nav-contact": "Hubungi Saya",
            "about-title": "Tentang Saya",
            "about-1": `Hai! Saya <strong>Chang Dick Shen</strong>, tetapi anda boleh memanggil saya <strong>DSON</strong>. Saya seorang pelajar reka bentuk multimedia dengan minat mendalam dalam mencipta pengalaman digital yang menarik dan bermakna. Kepakaran saya termasuk penyuntingan video, reka bentuk UI/UX, dan saya juga gemar menjelajah dunia animasi dan reka bentuk permainan.`,
            "about-2": `Saya berkongsi isi kandungan kreatif saya di pelbagai platform, termasuk <strong><a href="https://www.youtube.com/@dson.0404" target="_blank">YouTube</a></strong>, <strong><a href="https://space.bilibili.com/318162425/" target="_blank">Bilibili</a></strong>, <strong><a href="https://www.instagram.com/dson_04/" target="_blank">Instagram</a></strong>, <strong><a href="https://www.tiktok.com/@dson.04" target="_blank">TikTok</a></strong>, <strong><a href="https://www.xiaohongshu.com/user/profile/5d60f1db00000000010029cf" target="_blank">Xiaohongshu</a></strong>, dan <strong><a href="https://twitter.com/DSON_04" target="_blank">X (Twitter)</a></strong>. Antara platform ini, YouTube dan Bilibili adalah ruang utama saya untuk berkongsi karya kreatif.`,
            "about-3": `Misi saya adalah mengubah kreativiti menjadi karya yang memberi kesan, menginspirasikan, dan menghubungkan. Sila lihat portfolio saya atau hubungi saya melalui media sosial—saya amat teruja untuk berkongsi minat saya dengan anda!`,
            "footer-text": "© 2025 DSON. Semua hak terpelihara.",
            // 3d-modeling.html
            "title-section-1": "Rekabentuk Dalaman Pemodelan 3D",
            "title-section-2": "Video Showreel Reka Bentuk Watak 3D & Persekitaran",
            "title-section-3": "Pemodelan 3D Produk",
            "video-caption": "Video Showreel Reka Bentuk Watak 3D & Persekitaran saya.",
            "alt-final-2": "Sudut sisi dapur (kanan)",
            "alt-final-3": "Sudut sisi dapur (kiri)",
            "alt-final-4": "Sudut depan dapur",
            "alt-final-5": "Sudut kiri dapur (close up)",
            "alt-final-6": "Sudut kanan dapur (close up)",
            "keyboard-1": "Pemodelan 3D Papan Kekunci Mekanikal 1",
            "keyboard-2": "Pemodelan 3D Papan Kekunci Mekanikal 2",
            "keyboard-3": "Pemodelan 3D Papan Kekunci Mekanikal 3",
            "keyboard-4": "Pemodelan 3D Papan Kekunci Mekanikal 4",
            "keyboard-5": "Pemodelan 3D Papan Kekunci Mekanikal 5",
            "keyboard-6": "Pemodelan 3D Papan Kekunci Mekanikal 6",
            // 404.html
            "title": "404 Tidak Ditemui",
            "error-title": "404 - Halaman Tidak Ditemui",
            "error-text": "Halaman yang anda cari tidak wujud.",
            // contact.html
            "contact-title": "Tulis Sesuatu untuk Saya!",
            "contact-name": "Nama (Nama Penuh atau Nama Panggilan)",
            "contact-gender": "Jantina (Lelaki / Perempuan)",
            "contact-age": "Umur (0 ~ 99+)",
            "contact-email": "Emel",
            "contact-message": "Mesej",
            "contact-btn": "Hantar!",
            // illustration.html
            "title-illustration": "DSON | Manipulasi Imej & Seni Piksel",
            "section-image-manipulation": "Manipulasi Imej",
            "section-pixel-arts": "Seni Piksel",
            "img-apocalypse": "Apocalypse",
            "img-substance": "Penyalahgunaan Bahan",
            "pixel-boy": "Rekaan Watak 2D (Lelaki)",
            "pixel-girl": "Rekaan Watak 2D (Perempuan)",
            "pixel-soldier": "Askar Piksel",
            "pixel-poster": "Poster Seni Piksel",
            // photo.html
            "title": "DSON Fotografi | Siang, Malam & Fotografi Pergerakan",
            "photo-day": "Fotografi Waktu Siang",
            "photo-night": "Fotografi Senja atau Malam",
            "photo-motion": "Pergerakan dan Kedalaman Medan",
            "photo-edit": "Suntingan Foto",
            "edit-chess": "Kesan Neon Catur",
            "edit-cyber": "Kesan Jalanan Cyberpunk",
            "edit-80s": "Gaya Nostalgia 80-an",
            "edit-makoto": "Kesan Gaya Shinkai Makoto",
            "edit-city": "Kesan Pemandangan Bandar Malam",
            "alt-day-1": "Foto waktu siang 1",
            "alt-day-2": "Foto waktu siang 2",
            "alt-day-3": "Foto waktu siang 3",
            "alt-day-4": "Foto waktu siang 4",
            "alt-day-5": "Foto waktu siang 5",
            "alt-day-6": "Foto waktu siang 6",
            "alt-day-7": "Foto waktu siang 7",
            "alt-day-8": "Foto waktu siang 8",
            "alt-dusk-1": "Foto senja 1",
            "alt-dusk-2": "Foto senja 2",
            "alt-dusk-3": "Foto senja 3",
            "alt-dusk-4": "Foto senja 4",
            "alt-night-1": "Foto malam 1",
            "alt-night-2": "Foto malam 2",
            "alt-night-3": "Foto malam 3",
            "alt-night-4": "Foto malam 4",
            "alt-fast-1": "Foto pergerakan shutter laju 1",
            "alt-fast-2": "Foto pergerakan shutter laju 2",
            "alt-slow-1": "Foto kabur pergerakan shutter perlahan 1",
            "alt-slow-2": "Foto kabur pergerakan shutter perlahan 2",
            "alt-depth-1": "Foto kedalaman medan tinggi 1",
            "alt-depth-2": "Foto kedalaman medan tinggi 2",
            "alt-shallow-1": "Foto kedalaman medan cetek 1",
            "alt-shallow-2": "Foto kedalaman medan cetek 2",
            // social-media.html
            "title": "Portfolio Media Sosial DSON | Statistik YouTube, Bilibili, Instagram, TikTok",
            "socialmedia-title": "Media Sosial",
            "socialmedia-page": "Halaman Media Sosial",
            "socialmedia-click": "Klik halaman untuk melihat lebih banyak data!",
            "alt-yt": "Halaman YouTube",
            "alt-bili": "Halaman Bilibili",
            "alt-ig": "Halaman Instagram",
            "alt-x": "Halaman X",
            "alt-tt": "Halaman TikTok",
            "alt-xhs": "Halaman Xiaohongshu",
            "stats-subs": "Langganan:",
            "stats-followers": "Pengikut:",
            "stats-totalviews": "Jumlah tontonan:",
            "date-suffix": "(19/05/2025)",
            // socialmedia.html
            "title-uiux": "Portfolio UI/UX DSON | Rekaan Aplikasi Mudah Alih & Antara Muka Web",
            "section-uiux": "Rekaan UI/UX",
            "uiux-ocean-title": "Ocean Guardian",
            "uiux-ocean-desc": "Ocean Guardian adalah aplikasi mudah alih yang meningkatkan kesedaran tentang pencemaran laut dan menggalakkan pengguna untuk bertindak. Ia menyediakan notifikasi ekosistem, mempromosikan aktiviti sukarela, dan membolehkan pengguna berkongsi pencapaian. Aplikasi ini bertujuan membina komuniti yang membantu memulihkan dan melindungi lautan kita, menjadikannya lebih bersih dan lebih hidup.",
            "uiux-mnowner-title": "MnOwner",
            "uiux-mnowner-desc": "MnOwner membantu menyelesaikan masalah parkir berganda di Malaysia dengan mengingatkan pemandu supaya parkir dengan bertanggungjawab. Ia mengurangkan konflik, menjimatkan masa, dan mewujudkan budaya parkir yang lebih prihatin, sambil menyokong trafik yang lebih lancar dan kemudahan komuniti.",
            "uiux-partners": "(Rakan kongsi saya, Kai & Kean)",
            // video.html
            "title-video": "Portfolio Video DSON | Filem Pendek, Animasi, Grafik Gerak & Penyuntingan",
            "section-shortfilm": "Filem Pendek",
            "caption-klcity": "KL City Scene - Filem pendek memaparkan suasana bandaraya Kuala Lumpur yang meriah.",
            "caption-scammer": "Say No To Scammer - Filem pendek anti-penipuan dengan plot berliku. (Rakan kongsi saya, Kai & Kean)",
            "section-animation": "Video Animasi",
            "caption-littlefox-teaser": "Little Fox Childish Adventure teaser - Tayang pratonton video animasi. (Animasi oleh rakan saya, Kean)",
            "caption-littlefox-full": "Little Fox Childish Adventure - Video animasi pendek. (Animasi oleh rakan saya, Kean)",
            "caption-motion-final": "Tugasan Akhir Animasi - Animasi oleh rakan saya, Kean",
            "section-motiongraphic": "Grafik Gerak",
            "caption-dsonintro": "DSON Intro - Intro video YouTube saya.",
            "caption-mco": "MCO - Video tipografi bergerak.",
            "caption-spiderman": "Spider-Man - Treler filem.",
            "caption-visualmusic": "Visual Music.",
            "caption-mixmedia": "Mix Media.",
            "section-moviedubbing": "Suntingan Suara Filem",
            "caption-ipman1": "Ip Man Final Season Fighting Part - Audio telah disunting semula.",
            "caption-ipman2": "Ip Man spoof trailer - Disunting oleh 小芃路子野 dan saya sunting semula audio.",
            "section-productvideo": "Video Produk",
            "caption-aula": "AULA F75 Mechanical Keyboard Video Produk.",
            "section-psvideo": "Video Khidmat Masyarakat",
            "caption-corruption": "Video Khidmat Masyarakat Anti-Rasuah.",
            "section-musicvideo": "Video Muzik",
            "caption-luv": "LUV (Ori Music 'Blue' - Yung Kai) - Video Muzik Semula.",
            "caption-codm": "CODM WC 2025 Video Muzik Tidak Rasmi.",
        }
    };

    window.switchLang = function (lang) {
        document.querySelectorAll("[data-lang]").forEach(node => {
            const key = node.getAttribute("data-lang");
            if (translations[lang] && translations[lang][key]) {
                if (node.tagName === "IMG") {
                    node.alt = translations[lang][key];
                } else {
                    node.innerHTML = translations[lang][key];
                }
            }
        });

        document.querySelectorAll("[data-lang-placeholder]").forEach(node => {
            const key = node.getAttribute("data-lang-placeholder");
            if (translations[lang] && translations[lang][key]) {
                node.placeholder = translations[lang][key];
            }
        });

        if (translations[lang]["title"]) {
            document.title = translations[lang]["title"];
        }
    };

    document.querySelectorAll("[data-lang-select]").forEach(btn => {
        btn.addEventListener("click", (e) => {
            e.preventDefault();
            const lang = btn.getAttribute("data-lang-select");
            switchLang(lang);
        });
    });

    const switchBtn = document.getElementById("languageSwitch");
    const menu = document.getElementById("languageMenu");

    if (switchBtn && menu) {
        switchBtn.addEventListener("click", () => {
            menu.style.display = menu.style.display === "flex" ? "none" : "flex";
        });

        document.addEventListener("click", (e) => {
            if (!switchBtn.contains(e.target) && !menu.contains(e.target)) {
                menu.style.display = "none";
            }
        });
    }

    switchLang("en");
});